### PR TITLE
Bug: Fix CORS Header Issues

### PR DESCRIPTION
**Pull request by kylemellander**
### What does this PR do?

The way our current ember apps are loaded, they have a different port for the actual app and the resources.  That creates CORS errors.  This PR adds a little code to set the header 'Access-Control-Allow-Origin' on all responses that are made to these resources. 

This also upgrades ember, ember-cli, and ember-data to the latest versions.

### How to QA?

- [ ] In this project, run `npm install` and then 'npm link'
- [ ] In [Revelation Frontend Admin](https://invent.focusvision.com/Portland/revelation-frontend-admin),
    - [ ] NOMBOM
- [ ] run `npm link ember-cli-revelation-ui` and then start up the app.  Make sure that Admin is on [this branch](https://invent.focusvision.com/Portland/revelation-frontend-admin/tree/bug/km/fix-cors)
- [ ] Go to the ember admin and verify that the icons on the vertical nav are present.  Hard reload to make sure that cached icons aren't displaying.
- [ ] In [Revelation Frontend Participant](https://invent.focusvision.com/Portland/revelation-frontend-participant), run `npm link ember-cli-revelation-ui` and then start up the app.
- [ ] Go to the [ember participant](http://localhost:3000/cli/ep/) and verify that the icons on the vertical nav are present.  Hard reload to make sure that cached icons aren't displaying.

### CODE REVIEW

**Comment by zulaica** [comment]
+1

**Comment by smashedlife** [comment]
+1

**Comment by kscherling** [comment]
@kylemellander For some reason I can't pull branch... In fact, it doesn't even show up when I list remote branches.  Weird...  I think there might be an issue with the colon in your branch names.  Any ideas?

**Comment by kylemellander** [comment]
@kscherling Sorry about that!  I have it pulling from my fork.  I pushed it to this repos branches and it should be available now.

**Pull request merged**
