### PR TITLE
Loading Spinner

### PR DESCRIPTION
**Pull request by kylemellander**
This adds a loading spinner to addon for page loads.  This is associated with a PR from the admin repo.

### CODE REVIEW

**Comment by kscherling** [comment]
+1

**Comment by etozzato** [comment]
(this is never localizable, correct?)

+1

**Comment by kylemellander** [comment]
Unfortunately at this point there is no support for localization for this.  We could allow for a variable input for 'loading' that would override the default text here and could be configurable based on the localization on the main app.

**Comment by kylemellander** [comment]
In fact, let me add that in.

**Comment by kylemellander** [comment]
There is now support for localization (not built in, but it supports it)

**Pull request merged**
